### ISSUE TITLE
Please merge in the open PR (#3)

### ISSUE THREAD

**Issue by matthewtrianoUL** [conda-forge/bayesian-optimization-feedstock#4]
Is the update PR from the regro-cf-autotick-bot good to merge?

I'm pretty inexperienced with conda-forge feedstock maintaining (I've pretty much only read through the documentation on maintaining packages and created a recipe for a basic package that wasn't worth publishing), but from looking through the changes in the source code from [v1.1.0 to v 1.2.0](https://github.com/fmfn/BayesianOptimization/compare/v1.1.0...1.2.0#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7), there haven't been any changes to dependencies (which is the only issue the [documentation](https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch) cites as a reason why the branch generated by the regro-cf-autotick-bot would need manual intervention from a maintainer).

So, could someone more experienced advise if the update PR is good to merge?
```python
if its_good_to_merge:
    from bayesian_optimization_feedstock import Maintainer
    Maintainer(request="Please merge in PR #3 , thank you") 
else:
    from conda_forge import SomeoneKnowledgable
    some_knowledge = SomeoneKnowledgable(
        request="What should I check or read to understand why PR #3 is not ready to be merged in?"
    )
    print(some_knowledge)
```

Thanks in advance. BTW, normally I wouldn't import things in such an odd way, but I didn't want to potentially bother two people (in case the maintainer was not knowledgeable or not available).

**Comment by volpatto** [comment]
Hi, @matthewtrianoUL.

Sorry for the trouble, I was flooded with GH notifications and just lost this feedstock update request. I am enabling the `automerge` bot soon. The package is now up-to-date. Please let me know if you still can't use the latest version.

**Comment by matthewtrianoUL** [comment]
Thank you for maintaining conda packages! I really appreciate it.
